//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Marriage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoomMessage
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public Nullable<int> RelationRequest_Id { get; set; }
        public Nullable<int> SenderUser_Id { get; set; }
        public Nullable<System.DateTime> MsgDate { get; set; }
        public Nullable<int> Entity_Order { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
