//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Marriage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public string MsgHeader { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string MsgType { get; set; }
        public string Messages1 { get; set; }
        public Nullable<System.DateTime> MsgDate { get; set; }
        public string MsgStatus { get; set; }
        public Nullable<int> ReciverUser_Id { get; set; }
        public Nullable<int> Person_Id { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Person Person { get; set; }
    }
}
