//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Marriage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Messages = new HashSet<Messages>();
            this.RegisterRequests = new HashSet<RegisterRequests>();
            this.PersonVisibleFlds = new HashSet<PersonVisibleFlds>();
            this.PersonHiddenFlds = new HashSet<PersonHiddenFlds>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Nationality_Id { get; set; }
        public string FullName { get; set; }
        public string Father { get; set; }
        public string Mother { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> Weight { get; set; }
        public string PlaceBirth { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Residence_Country_Id { get; set; }
        public Nullable<int> SocialStatus { get; set; }
        public string Color { get; set; }
        public string Gender { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string NationalityNumber { get; set; }
        public string PassportNumber { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string GeneralInfo { get; set; }
        public string NickName { get; set; }
        public string SurName { get; set; }
        public string CountryState { get; set; }
        public Nullable<byte> ChildCount { get; set; }
        public Nullable<byte> MaxChildAge { get; set; }
        public Nullable<byte> MinChildAge { get; set; }
        public string Education { get; set; }
        public string EducationBranch { get; set; }
        public string Work { get; set; }
        public string Languages { get; set; }
        public string LivingLevel { get; set; }
        public string Theams { get; set; }
        public string Hobbies { get; set; }
        public string Culture { get; set; }
        public string CultureLevel { get; set; }
        public string WorkType { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterRequests> RegisterRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonVisibleFlds> PersonVisibleFlds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonHiddenFlds> PersonHiddenFlds { get; set; }
    }
}
