//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Marriage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisterRequests()
        {
            this.RequestQuestionSenario = new HashSet<RequestQuestionSenario>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> Person_Id { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public Nullable<int> ResponseMessage { get; set; }
        public string Links { get; set; }
        public string RequestMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestQuestionSenario> RequestQuestionSenario { get; set; }
        public virtual Person Person { get; set; }
    }
}
