//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Marriage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RelationRequest()
        {
            this.ChatRoomMessage = new HashSet<ChatRoomMessage>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RequestUser_Id { get; set; }
        public Nullable<int> RegisterRequests_Id { get; set; }
        public Nullable<int> TargetUser_Id { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string RequestMessage { get; set; }
        public string ResponseMessage { get; set; }
        public string RequestStatus { get; set; }
        public Nullable<bool> AllowChatRoom { get; set; }
        public Nullable<int> ResponsibleManager_Id { get; set; }
    
        public virtual RegisterRequests RegisterRequests { get; set; }
        public virtual Users SourceUsers { get; set; }
        public virtual Users TargetUsers { get; set; }
        public virtual Users ResponseUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatRoomMessage> ChatRoomMessage { get; set; }
    }
}
