//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Marriage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestQuestionSenario
    {
        public int Id { get; set; }
        public Nullable<int> Question_id { get; set; }
        public string Answers { get; set; }
        public Nullable<int> RegisterRequests_Id { get; set; }
        public Nullable<int> Entity_Order { get; set; }
    
        public virtual QuestionBank QuestionBank { get; set; }
        public virtual RegisterRequests RegisterRequests { get; set; }
    }
}
