//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Marriage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermissions
    {
        public int Id { get; set; }
        public Nullable<int> Permission_Id { get; set; }
        public Nullable<int> Roles_Id { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Permissons Permissons { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
