//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Marriage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionBank
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Entity_Order { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
